services:
  acmehr-training-sp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      IDP_METADATA_URL: ${IDP_METADATA_URL:-}
      ACMEHR_SAML_SP_SIGNING_PRIVATE_KEY_LOCATION: ${ACMEHR_SAML_SP_SIGNING_PRIVATE_KEY_LOCATION:-}
      ACMEHR_SAML_SP_SIGNING_CERTIFICATE_LOCATION: ${ACMEHR_SAML_SP_SIGNING_CERTIFICATE_LOCATION:-}
      ACMEHR_SAML_SP_DECRYPTION_PRIVATE_KEY_LOCATION: ${ACMEHR_SAML_SP_DECRYPTION_PRIVATE_KEY_LOCATION:-}
      ACMEHR_SAML_SP_DECRYPTION_CERTIFICATE_LOCATION: ${ACMEHR_SAML_SP_DECRYPTION_CERTIFICATE_LOCATION:-}
      ACMEHR_SAML_NAME_ID_FORMAT: ${ACMEHR_SAML_NAME_ID_FORMAT:-}

  validation-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    profiles:
      - test
    command:
      - mvn
      - -B
      - -ntp
      - verify
